# Generated by Django 2.1.2 on 2018-10-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_operator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
