# Generated by Django 2.1.2 on 2018-10-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181018_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Submitter',
        ),
    ]
