# Generated by Django 2.1.2 on 2018-10-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181018_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RenameField(
            model_name='submitter',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='submitter',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
