# Generated by Django 2.1.2 on 2018-10-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181026_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitter',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
